### ISSUE TITLE
About the more detailed requirements for repo

### ISSUE THREAD

**Issue by fusheng-ji** [JojiJoseph/3dgs-gradient-segmentation#1]
Hi Joji,
thanks for your awesome work! As I successfully ran the demo.py. To make your work easier to followed, could you please add the additional requirements in your reuqirement.txt?
1. pip install tyro natsort
2. download 'sam2_hiera_large.pt' from https://huggingface.co/facebook/sam2-hiera-large/tree/main and put under ./checkpoints
3. pip install git+https://github.com/ultralytics/CLIP.git

Best regards

**Comment by JojiJoseph** [comment]
Thanks for pointing that out!

I’ve added the dependencies (`tyro`, `natsort`, `CLIP`) to `requirements.txt` and updated the README.md with instructions to download the [sam2-hiera-large](https://huggingface.co/facebook/sam2-hiera-large) checkpoint.

Thanks!
