### ISSUE TITLE
About segment

### ISSUE THREAD

**Issue by Luoyoooo** [JojiJoseph/3dgs-gradient-segmentation#3]
Dear author，I would like to ask if the final segmentation is just a series of segmented pictures. If I want to get the segmented Gaussian, do I need to go through training? Thanks

**Comment by JojiJoseph** [comment]
Thanks for raising this issue.

You need not train on the segmented images. You can use 3d mask (returned by `get_mask3d` function)  to filter the Gaussians and save it to disk.

I will add a utility function to do that by next week.

**Comment by Luoyoooo** [comment]
> 感谢您提出这个问题。
> 
> 您不需要在分割图像上进行训练。您可以使用 3d mask（由`get_mask3d`函数返回）来过滤高斯并将其保存到磁盘。
> 
> 我将在下周之前添加一个实用功能来实现这一点。

Thank you so much！

**Comment by JojiJoseph** [comment]
Hello, I modified ```demo.py``` to save the mask and added a script ```viewer.py``` to see the segmented region after segmentation.
